project:
  type: website
    
website:
  site-url: https://jiexu.github.io/
  repo-url: https://github.com/jiexu2776/jiexu.github.io/
  favicon: favicon.png
  title: "Jie Xu"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
